# -*- coding: utf-8 -*-
"""HW1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14WdmkMmIJVGT2TImFugv3Pypbkx2kPPA

**HW1**
地理113 陳惠 40923229L
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive/112_2_LATIA/") # 切換目錄
!ls -l "/content/gdrive/My Drive/112_2_LATIA/112oversea_B1-1a.csv" # 列出目錄下的檔案
#!ls -l "/content/gdrive/My Drive/112_2_LATIA/"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

csv_file = '/content/gdrive/My Drive/112_2_LATIA/112oversea_B1-1a.csv'

df = pd.read_csv(csv_file, encoding='utf-8') # 讀取csv檔案
print(df.head(), '\n')

#查看資料欄位資訊
print(df.info())

#查看資料的統計學資訊描述
#print(df.describe(include='all'))

# Colab 進行matplotlib繪圖時顯示繁體中文
# 下載台北思源黑體並命名taipei_sans_tc_beta.ttf，移至指定路徑
!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager

fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
mpl.rc('font', family='Taipei Sans TC Beta')

"""# 1.總共有多少國家的僑生？分別是哪些？"""

df = df.drop_duplicates(subset=['僑居地'])
count = df['僑居地'].value_counts()
degree_list = list(df['僑居地'].unique())

print(f"本年度共有 {len(df['僑居地'])} 個國家，分別來自：")
print('\n'.join(degree_list))

"""# 2. 畢業僑生數量最多的前十個國家是哪些？"""

# 將畢業生男女人數加總，以僑居地為分組依據
df1 = df[['僑居地', '上學年度畢業生人數_男', '上學年度畢業生人數_女']]
def sum_ab(df1):
  return df1['上學年度畢業生人數_男'] + df1['上學年度畢業生人數_女']

df1['總畢業生人數'] = df1.apply(sum_ab, axis=1)

grouped_data = df1.groupby('僑居地').agg({'總畢業生人數': 'sum'})

# 按總畢業生數量降序排序
sorted_data = grouped_data.sort_values(by='總畢業生人數', ascending=False)

# 列印前十名
print("畢業僑生數量最多的前十個國家是：")
print(sorted_data.head(10))

# 取前十名
top_ten_countries = sorted_data.head(10)

# 繪製長條圖
plt.figure(figsize=(10, 6))
plt.bar(top_ten_countries.index, top_ten_countries['總畢業生人數'], color='skyblue')
plt.xlabel('僑居地')
plt.ylabel('總畢業生人數')
plt.title('僑生畢業人數最多的前十個國家')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# 3.僑生新生入學人數最多的前十個國家是哪些？"""

df6 = df[['僑居地', '新生']]

#以僑居地為分組依據
grouped_data = df6.groupby('僑居地').agg('sum')

# 按新生人數降序排序
sorted_data = grouped_data.sort_values(by='新生', ascending=False)

# 找出前十個國家
print("新生入學人數最多的前十個國家是：")
print(sorted_data.head(10))

# 取前十名
top_ten_countries = sorted_data.head(10)

# 繪製長條圖
plt.figure(figsize=(10, 6))
plt.bar(top_ten_countries.index, top_ten_countries['新生'], color='pink')
plt.xlabel('僑居地')
plt.ylabel('新生人數')
plt.title('僑生新生入學人數最多的前十間學校')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# 4. 畢業僑生數量最多的前十間學校是哪些？"""

# 將畢業生男女人數加總，以僑居地為分組依據
df2 = df[['學校名稱', '上學年度畢業生人數_男', '上學年度畢業生人數_女']]
def sum_ab(df2):
  return df2['上學年度畢業生人數_男'] + df2['上學年度畢業生人數_女']

df2['總畢業生人數'] = df2.apply(sum_ab, axis=1)

grouped_data = df2.groupby('學校名稱').agg({'總畢業生人數': 'sum'})

# 按總畢業生數量降序排序
sorted_data = grouped_data.sort_values(by='總畢業生人數', ascending=False)

# 列印前十名
print("畢業僑生數量最多的前十間學校是：")
print(sorted_data.head(10))

# 取前十名
top_ten_school = sorted_data.head(10)

# 繪製長條圖
plt.figure(figsize=(10, 6))
plt.bar(top_ten_school.index, top_ten_school['總畢業生人數'], color='yellow')
plt.xlabel('學校名稱')
plt.ylabel('總畢業生人數')
plt.title('畢業僑生人數最多的前十名學校')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# 5. 來自亞洲、歐美洲的僑生分別有多少？

亞洲國家包含：中國、日本、韓國、印度、越南、泰國、菲律賓、馬來西亞、新加坡、印尼、巴基斯坦、孟加拉、伊朗、伊拉克、以色列、土耳其、沙烏地阿拉伯、阿聯酋

歐美國家包含：美國、 加拿大、 英國、 法國、 德國、 義大利、 西班牙、 俄羅斯、 荷蘭、 瑞士、 挪威、 瑞典、 丹麥、 芬蘭、 比利時、 希臘、 奧地利、 愛爾蘭、 葡萄牙、 波蘭、 捷克、 匈牙利、 斯洛伐克、 克羅地亞、 羅馬尼亞、 保加利亞、 塞爾維亞、 斯洛文尼亞、 拉脫維亞、 愛沙尼亞、 立陶宛、 波斯尼亞和黑塞哥維那、 阿爾巴尼亞、 馬其頓、 克里米亞、 摩爾多瓦、 白俄羅斯、 烏克蘭
"""

# 將畢業生男女人數加總，以僑居地為分組依據
df3 = df[['僑居地', '上學年度畢業生人數_男', '上學年度畢業生人數_女']]

def sum_ab(row):
    return row['上學年度畢業生人數_男'] + row['上學年度畢業生人數_女']

# 使用 .loc 賦值
df3['總畢業生人數'] = df3.apply(sum_ab, axis=1)

# 將僑居地分類為亞洲、歐美洲
asia_countries = ['中國', '日本', '韓國', '印度', '越南', '泰國', '菲律賓', '馬來西亞', '新加坡', '印尼', '巴基斯坦', '孟加拉', '伊朗', '伊拉克', '以色列', '土耳其', '沙烏地阿拉伯', '阿聯酋']
europe_america_countries = ['美國', '加拿大', '英國', '法國', '德國', '義大利', '西班牙', '俄羅斯', '荷蘭', '瑞士', '挪威', '瑞典', '丹麥', '芬蘭', '比利時', '希臘', '奧地利', '愛爾蘭', '葡萄牙', '波蘭', '捷克', '匈牙利', '斯洛伐克', '克羅埃西亞', '羅馬尼亞', '保加利亞', '塞爾維亞', '斯洛文尼亞', '拉脫維亞', '愛沙尼亞', '立陶宛', '波斯尼亞和黑塞哥維那', '阿爾巴尼亞', '馬其頓', '克里米亞', '摩爾多瓦', '白俄羅斯', '烏克蘭']

# 篩選亞洲僑生
asia_students = df3[df3['僑居地'].isin(asia_countries)]

# 篩選歐美洲僑生
europe_america_students = df3[df3['僑居地'].isin(europe_america_countries)]

# 計算亞洲僑生畢業總人數
asia_graduated_total = asia_students['總畢業生人數'].sum()

# 計算歐美洲僑生畢業總人數
europe_america_graduated_total = europe_america_students['總畢業生人數'].sum()

print("亞洲僑生畢業總人數：", asia_graduated_total)
print("歐美洲僑生畢業總人數：", europe_america_graduated_total)

graduated_total = [asia_graduated_total, europe_america_graduated_total]
labels = ['亞洲', '歐美洲']

# 繪製圓餅圖
plt.figure(figsize=(8, 6))
plt.pie(graduated_total, labels=labels, autopct='%1.1f%%', colors=['lightblue', 'lightgreen'], startangle=140)
plt.title('亞洲和歐美洲的畢業總人數比例')
plt.axis('equal')
plt.show()

"""# 6. 來自中東國家的在校僑生男女比是多少？

中東國家包含：巴林、埃及、伊朗、伊拉克、以色列、約旦、科威特、黎巴嫩、阿曼、卡達、沙烏地阿拉伯、敘利亞、阿拉伯聯合大公國、葉門、巴勒斯坦、馬格里布國家（阿爾及利亞、利比亞、摩洛哥、突尼西亞），以及蘇丹共和國、茅利塔尼亞和索馬利亞，由於阿拉伯世界歷史文化原因，一般人們認為屬於中東國家；土耳其和賽普勒斯亦歸類於地理上的中東國家。
"""

df4 = df[['僑居地', '在學學生人數_男', '在學學生人數_女']]

# 定義中東國家列表
middle_east_countries = ['巴林', '埃及', '伊朗', '伊拉克', '以色列', '約旦', '科威特', '黎巴嫩', '阿曼', '卡達', '沙烏地阿拉伯', '敘利亞', '阿拉伯聯合大公國', '葉門', '巴勒斯坦', '阿爾及利亞', '利比亞', '摩洛哥', '突尼西亞', '蘇丹共和國', '茅利塔尼亞', '索馬利亞', '土耳其', '賽普勒斯']

# 篩選中東國家的僑生
middle_east_students = df4[df4['僑居地'].isin(middle_east_countries)]

# 計算男女比例
total_male_students = middle_east_students['在學學生人數_男'].sum()
total_female_students = middle_east_students['在學學生人數_女'].sum()
ratio = total_male_students/total_female_students*100

print(f'中東國家的在校僑生男女比：{ratio} ≑ {round(ratio,2)}')

graduated_total = [total_male_students, total_female_students]
labels = ['男生', '女生']

# 繪製圓餅圖
plt.figure(figsize=(8, 6))
plt.pie(graduated_total, labels=labels, autopct='%1.1f%%', colors=['lightblue', 'lightgreen'], startangle=140)
plt.title('中東國家的在校僑生男女比')
plt.axis('equal')
plt.show()